-- MySQL Script generated by MySQL Workbench
-- 03/07/15 19:22:58
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema hoverboard_esgi
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hoverboard_esgi
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hoverboard_esgi` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `hoverboard_esgi` ;

-- -----------------------------------------------------
-- Table `hoverboard_esgi`.`version`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hoverboard_esgi`.`version` (
  `idVersion` INT NOT NULL AUTO_INCREMENT,
  `dateUpdate` DATE NOT NULL,
  `numVersion` VARCHAR(60) NOT NULL,
  `changelog` VARCHAR(200) NOT NULL,
  `pathToVersion` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idVersion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hoverboard_esgi`.`type_widget`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hoverboard_esgi`.`type_widget` (
  `idTypeWidget` INT NOT NULL AUTO_INCREMENT,
  `nomTypeWidget` VARCHAR(45) NOT NULL,
  `descriptionTypeWidget` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idTypeWidget`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hoverboard_esgi`.`dashboard`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hoverboard_esgi`.`dashboard` (
  `idDashboard` INT NOT NULL AUTO_INCREMENT,
  `titleDashboard` VARCHAR(45) NOT NULL,
  `descriptionDashboard` VARCHAR(200) NULL,
  `isShared` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`idDashboard`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hoverboard_esgi`.`widgets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hoverboard_esgi`.`widgets` (
  `idWidget` INT NOT NULL AUTO_INCREMENT,
  `contentWidget` VARCHAR(45) NULL,
  `positionX` INT NOT NULL,
  `positionY` INT NOT NULL,
  `longueur` INT NOT NULL,
  `largeur` INT NOT NULL,
  `idDashboard` INT NOT NULL,
  `idTypeWidget` INT NOT NULL,
  PRIMARY KEY (`idWidget`),
  INDEX `fk_widgets_type_widget1_idx` (`idTypeWidget` ASC),
  INDEX `fk_widgets_dashboard1_idx` (`idDashboard` ASC),
  CONSTRAINT `fk_widgets_type_widget1`
    FOREIGN KEY (`idTypeWidget`)
    REFERENCES `hoverboard_esgi`.`type_widget` (`idTypeWidget`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_widgets_dashboard1`
    FOREIGN KEY (`idDashboard`)
    REFERENCES `hoverboard_esgi`.`dashboard` (`idDashboard`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hoverboard_esgi`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hoverboard_esgi`.`users` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `isAdmin` TINYINT(1) NOT NULL DEFAULT 0,
  `isActive` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hoverboard_esgi`.`application`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hoverboard_esgi`.`application` (
  `idApplication` INT NOT NULL AUTO_INCREMENT,
  `nameApplication` VARCHAR(45) NOT NULL,
  `dateReleaseApp` DATE NOT NULL,
  PRIMARY KEY (`idApplication`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hoverboard_esgi`.`plugins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hoverboard_esgi`.`plugins` (
  `idPlugin` INT NOT NULL AUTO_INCREMENT,
  `namePlugin` VARCHAR(60) NOT NULL,
  `descriptionPlugin` VARCHAR(100) NOT NULL,
  `dateRelease` DATE NOT NULL,
  `isValid` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`idPlugin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hoverboard_esgi`.`statut_plugin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hoverboard_esgi`.`statut_plugin` (
  `idStatutPlugin` INT NOT NULL AUTO_INCREMENT,
  `labelStatutPlugin` VARCHAR(45) NULL,
  PRIMARY KEY (`idStatutPlugin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hoverboard_esgi`.`utilise`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hoverboard_esgi`.`utilise` (
  `idUser` INT NOT NULL,
  `idDashboard` INT NOT NULL,
  `isDashboardAdmin` TINYINT(1) NULL,
  PRIMARY KEY (`idUser`, `idDashboard`),
  INDEX `fk_Users_has_Dashboard_Dashboard1_idx` (`idDashboard` ASC),
  INDEX `fk_Users_has_Dashboard_Users_idx` (`idUser` ASC),
  CONSTRAINT `fk_Users_has_Dashboard_Users`
    FOREIGN KEY (`idUser`)
    REFERENCES `hoverboard_esgi`.`users` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Users_has_Dashboard_Dashboard1`
    FOREIGN KEY (`idDashboard`)
    REFERENCES `hoverboard_esgi`.`dashboard` (`idDashboard`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hoverboard_esgi`.`telecharge`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hoverboard_esgi`.`telecharge` (
  `idPlugin` INT NOT NULL,
  `idUser` INT NOT NULL,
  `idStatutPlugin` INT NOT NULL,
  PRIMARY KEY (`idPlugin`, `idUser`),
  INDEX `fk_Plugins_has_Users_Users1_idx` (`idUser` ASC),
  INDEX `fk_Plugins_has_Users_Plugins1_idx` (`idPlugin` ASC),
  INDEX `fk_Plugins_has_Users_StatutPlugin1_idx` (`idStatutPlugin` ASC),
  CONSTRAINT `fk_Plugins_has_Users_Plugins1`
    FOREIGN KEY (`idPlugin`)
    REFERENCES `hoverboard_esgi`.`plugins` (`idPlugin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Plugins_has_Users_Users1`
    FOREIGN KEY (`idUser`)
    REFERENCES `hoverboard_esgi`.`users` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Plugins_has_Users_StatutPlugin1`
    FOREIGN KEY (`idStatutPlugin`)
    REFERENCES `hoverboard_esgi`.`statut_plugin` (`idStatutPlugin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hoverboard_esgi`.`version_plugin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hoverboard_esgi`.`version_plugin` (
  `idPlugin` INT NOT NULL,
  `idVersion` INT NOT NULL,
  PRIMARY KEY (`idPlugin`, `idVersion`),
  INDEX `fk_Plugins_has_Version_Version1_idx` (`idVersion` ASC),
  INDEX `fk_Plugins_has_Version_Plugins1_idx` (`idPlugin` ASC),
  CONSTRAINT `fk_Plugins_has_Version_Plugins1`
    FOREIGN KEY (`idPlugin`)
    REFERENCES `hoverboard_esgi`.`plugins` (`idPlugin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Plugins_has_Version_Version1`
    FOREIGN KEY (`idVersion`)
    REFERENCES `hoverboard_esgi`.`version` (`idVersion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hoverboard_esgi`.`version_application`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hoverboard_esgi`.`version_application` (
  `idApplication` INT NOT NULL,
  `idVersion` INT NOT NULL,
  PRIMARY KEY (`idApplication`, `idVersion`),
  INDEX `fk_Application_has_Version_Version1_idx` (`idVersion` ASC),
  INDEX `fk_Application_has_Version_Application1_idx` (`idApplication` ASC),
  CONSTRAINT `fk_Application_has_Version_Application1`
    FOREIGN KEY (`idApplication`)
    REFERENCES `hoverboard_esgi`.`application` (`idApplication`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Application_has_Version_Version1`
    FOREIGN KEY (`idVersion`)
    REFERENCES `hoverboard_esgi`.`version` (`idVersion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hoverboard_esgi`.`apparente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hoverboard_esgi`.`apparente` (
  `idPlugin` INT NOT NULL,
  `idTypeWidget` INT NOT NULL,
  PRIMARY KEY (`idPlugin`, `idTypeWidget`),
  INDEX `fk_plugins_has_type_widget_type_widget1_idx` (`idTypeWidget` ASC),
  INDEX `fk_plugins_has_type_widget_plugins1_idx` (`idPlugin` ASC),
  CONSTRAINT `fk_plugins_has_type_widget_plugins1`
    FOREIGN KEY (`idPlugin`)
    REFERENCES `hoverboard_esgi`.`plugins` (`idPlugin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_plugins_has_type_widget_type_widget1`
    FOREIGN KEY (`idTypeWidget`)
    REFERENCES `hoverboard_esgi`.`type_widget` (`idTypeWidget`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
