-- MySQL Script generated by MySQL Workbench
-- 02/13/15 17:05:35
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema hoverboard_jx90
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hoverboard_jx90
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hoverboard_jx90` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `hoverboard_jx90` ;

-- -----------------------------------------------------
-- Table `hoverboard_jx90`.`version`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hoverboard_jx90`.`version` (
  `idVersion` INT NOT NULL AUTO_INCREMENT,
  `dateUpdate` DATE NOT NULL,
  `numVersion` VARCHAR(60) NOT NULL,
  `changelog` VARCHAR(200) NOT NULL,
  `pathToVersion` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idVersion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hoverboard_jx90`.`dashboard`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hoverboard_jx90`.`dashboard` (
  `idDashboard` INT NOT NULL AUTO_INCREMENT,
  `titleDashboard` VARCHAR(45) NOT NULL,
  `isShared` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`idDashboard`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hoverboard_jx90`.`type_post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hoverboard_jx90`.`type_post` (
  `idTypePost` INT NOT NULL AUTO_INCREMENT,
  `nomTypePost` VARCHAR(45) NOT NULL,
  `descriptionTypePost` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idTypePost`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hoverboard_jx90`.`elements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hoverboard_jx90`.`elements` (
  `idElement` INT NOT NULL AUTO_INCREMENT,
  `contentElement` VARCHAR(45) NOT NULL,
  `positionX` INT NOT NULL,
  `positionY` INT NOT NULL,
  `longueur` INT NOT NULL,
  `largeur` INT NOT NULL,
  `idDashboard` INT NOT NULL,
  `idTypePost` INT NOT NULL,
  PRIMARY KEY (`idElement`),
  INDEX `fk_Elements_Dashboard1_idx` (`idDashboard` ASC),
  INDEX `fk_Elements_TypePost1_idx` (`idTypePost` ASC),
  CONSTRAINT `fk_Elements_Dashboard1`
    FOREIGN KEY (`idDashboard`)
    REFERENCES `hoverboard_jx90`.`dashboard` (`idDashboard`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Elements_TypePost1`
    FOREIGN KEY (`idTypePost`)
    REFERENCES `hoverboard_jx90`.`type_post` (`idTypePost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hoverboard_jx90`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hoverboard_jx90`.`users` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `lastName` VARCHAR(45) NOT NULL,
  `firstName` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `isAdmin` TINYINT(1) NOT NULL DEFAULT 0,
  `isActive` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hoverboard_jx90`.`application`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hoverboard_jx90`.`application` (
  `idApplication` INT NOT NULL AUTO_INCREMENT,
  `nameApplication` VARCHAR(45) NOT NULL,
  `dateReleaseApp` DATE NOT NULL,
  PRIMARY KEY (`idApplication`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hoverboard_jx90`.`plugins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hoverboard_jx90`.`plugins` (
  `idPlugin` INT NOT NULL AUTO_INCREMENT,
  `namePlugin` VARCHAR(60) NOT NULL,
  `descriptionPlugin` VARCHAR(100) NOT NULL,
  `dateRelease` DATE NOT NULL,
  `isValid` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`idPlugin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hoverboard_jx90`.`statut_plugin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hoverboard_jx90`.`statut_plugin` (
  `idStatutPlugin` INT NOT NULL AUTO_INCREMENT,
  `labelStatutPlugin` VARCHAR(45) NULL,
  PRIMARY KEY (`idStatutPlugin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hoverboard_jx90`.`utilise`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hoverboard_jx90`.`utilise` (
  `idUser` INT NOT NULL,
  `idDashboard` INT NOT NULL,
  `idDashboardAdmin` TINYINT(1) NULL,
  PRIMARY KEY (`idUser`, `idDashboard`),
  INDEX `fk_Users_has_Dashboard_Dashboard1_idx` (`idDashboard` ASC),
  INDEX `fk_Users_has_Dashboard_Users_idx` (`idUser` ASC),
  CONSTRAINT `fk_Users_has_Dashboard_Users`
    FOREIGN KEY (`idUser`)
    REFERENCES `hoverboard_jx90`.`users` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Users_has_Dashboard_Dashboard1`
    FOREIGN KEY (`idDashboard`)
    REFERENCES `hoverboard_jx90`.`dashboard` (`idDashboard`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hoverboard_jx90`.`telecharge`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hoverboard_jx90`.`telecharge` (
  `idPlugin` INT NOT NULL,
  `idUser` INT NOT NULL,
  `idStatutPlugin` INT NOT NULL,
  PRIMARY KEY (`idPlugin`, `idUser`),
  INDEX `fk_Plugins_has_Users_Users1_idx` (`idUser` ASC),
  INDEX `fk_Plugins_has_Users_Plugins1_idx` (`idPlugin` ASC),
  INDEX `fk_Plugins_has_Users_StatutPlugin1_idx` (`idStatutPlugin` ASC),
  CONSTRAINT `fk_Plugins_has_Users_Plugins1`
    FOREIGN KEY (`idPlugin`)
    REFERENCES `hoverboard_jx90`.`plugins` (`idPlugin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Plugins_has_Users_Users1`
    FOREIGN KEY (`idUser`)
    REFERENCES `hoverboard_jx90`.`users` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Plugins_has_Users_StatutPlugin1`
    FOREIGN KEY (`idStatutPlugin`)
    REFERENCES `hoverboard_jx90`.`statut_plugin` (`idStatutPlugin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hoverboard_jx90`.`apparente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hoverboard_jx90`.`apparente` (
  `idPlugin` INT NOT NULL,
  `idTypePost` INT NOT NULL,
  PRIMARY KEY (`idPlugin`, `idTypePost`),
  INDEX `fk_Plugins_has_TypePost_TypePost1_idx` (`idTypePost` ASC),
  INDEX `fk_Plugins_has_TypePost_Plugins1_idx` (`idPlugin` ASC),
  CONSTRAINT `fk_Plugins_has_TypePost_Plugins1`
    FOREIGN KEY (`idPlugin`)
    REFERENCES `hoverboard_jx90`.`plugins` (`idPlugin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Plugins_has_TypePost_TypePost1`
    FOREIGN KEY (`idTypePost`)
    REFERENCES `hoverboard_jx90`.`type_post` (`idTypePost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hoverboard_jx90`.`version_plugin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hoverboard_jx90`.`version_plugin` (
  `idPlugin` INT NOT NULL,
  `idVersion` INT NOT NULL,
  PRIMARY KEY (`idPlugin`, `idVersion`),
  INDEX `fk_Plugins_has_Version_Version1_idx` (`idVersion` ASC),
  INDEX `fk_Plugins_has_Version_Plugins1_idx` (`idPlugin` ASC),
  CONSTRAINT `fk_Plugins_has_Version_Plugins1`
    FOREIGN KEY (`idPlugin`)
    REFERENCES `hoverboard_jx90`.`plugins` (`idPlugin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Plugins_has_Version_Version1`
    FOREIGN KEY (`idVersion`)
    REFERENCES `hoverboard_jx90`.`version` (`idVersion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hoverboard_jx90`.`version_application`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hoverboard_jx90`.`version_application` (
  `idApplication` INT NOT NULL,
  `idVersion` INT NOT NULL,
  PRIMARY KEY (`idApplication`, `idVersion`),
  INDEX `fk_Application_has_Version_Version1_idx` (`idVersion` ASC),
  INDEX `fk_Application_has_Version_Application1_idx` (`idApplication` ASC),
  CONSTRAINT `fk_Application_has_Version_Application1`
    FOREIGN KEY (`idApplication`)
    REFERENCES `hoverboard_jx90`.`application` (`idApplication`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Application_has_Version_Version1`
    FOREIGN KEY (`idVersion`)
    REFERENCES `hoverboard_jx90`.`version` (`idVersion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
